import libraries

In [1]:
import pandas as pd
import numpy as np

load and summarize dataset

In [2]:
df = pd.read_csv('dataset.csv')

In [3]:
df.head()

Age  Salary  Status
0   26   80000       0
1   35   22000       0
2   35   39000       0
3   49   74000       0
4   39  134000       1

In [4]:
df.shape

(216, 3)

segregate dataset into x and y

In [5]:
x = df.iloc[:, :-1].values
x

array([[    26,  80000],
       [    35,  22000],
       [    35,  39000],
       [    49,  74000],
       [    39, 134000],
       [    41,  71000],
       [    58, 101000],
       [    47,  47000],
       [    55, 130000],
       [    52, 114000],
       [    40, 142000],
       [    46,  22000],
       [    48,  96000],
       [    52, 150000],
       [    59,  42000],
       [    35,  58000],
       [    47,  43000],
       [    60, 108000],
       [    49,  65000],
       [    40,  78000],
       [    46,  96000],
       [    59, 143000],
       [    41,  80000],
       [    35,  91000],
       [    37, 144000],
       [    60, 102000],
       [    35,  60000],
       [    37,  53000],
       [    36, 126000],
       [    56, 133000],
       [    40,  72000],
       [    42,  80000],
       [    35, 147000],
       [    39,  42000],
       [    40, 107000],
       [    49,  86000],
       [    38, 112000],
       [    46,  79000],
       [    40,  57000],
       [    37,  80000],


In [6]:
y = df.iloc[:, -1].values
y

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

spliiting dataset to tarin and test

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

feature scaling (standardization - zscore & normalization - min_max_normalization

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [9]:
x_train

array([[-0.92509862,  0.03401961],
       [ 0.06014155, -1.11414237],
       [ 0.49802607,  0.34976416],
       [-0.92509862, -0.51135733],
       [ 0.16961268,  1.52663019],
       [-0.81562749,  0.6081006 ],
       [-0.37774297, -0.51135733],
       [ 1.26432398,  1.49792614],
       [ 0.27908381,  0.12013176],
       [-0.59668523, -0.19561278],
       [ 0.93591059,  2.07200713],
       [-0.15880071, -0.22431683],
       [-0.37774297, -0.19561278],
       [-0.70615636,  1.89978283],
       [-0.37774297, -0.16690873],
       [ 1.59273736,  0.49328441],
       [ 0.71696833, -0.97062212],
       [-0.81562749,  1.35440589],
       [-0.4872141 ,  1.61274234],
       [-0.37774297,  0.00531556],
       [-0.04932958,  1.46922209],
       [ 1.15485285, -0.22431683],
       [ 0.49802607,  1.61274234],
       [ 0.27908381, -1.05673427],
       [-0.92509862,  0.55069251],
       [-0.92509862, -0.08079658],
       [-0.4872141 , -0.19561278],
       [ 0.82643946,  1.61274234],
       [-0.70615636,

model training

In [10]:
from sklearn.linear_model import LogisticRegression

# loading the algorithm
model = LogisticRegression() 

# train the model
model.fit(x_train, y_train)

LogisticRegression()

In [11]:
# using help() we can check that the attributes of the model

help(LogisticRegression)

Help on class LogisticRegression in module sklearn.linear_model._logistic:

class LogisticRegression(sklearn.linear_model._base.LinearClassifierMixin, sklearn.linear_model._base.SparseCoefMixin, sklearn.base.BaseEstimator)
 |  LogisticRegression(penalty='l2', *, dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
 |  
 |  Logistic Regression (aka logit, MaxEnt) classifier.
 |  
 |  In the multiclass case, the training algorithm uses the one-vs-rest (OvR)
 |  scheme if the 'multi_class' option is set to 'ovr', and uses the
 |  cross-entropy loss if the 'multi_class' option is set to 'multinomial'.
 |  (Currently the 'multinomial' option is supported only by the 'lbfgs',
 |  'sag', 'saga' and 'newton-cg' solvers.)
 |  
 |  This class implements regularized logistic regression using the
 |  'liblinear' library, 'newton-cg', 's

validation process

In [12]:
y_pred =  model.predict(x_test)

In [13]:
from sklearn.metrics import accuracy_score

print("Accuracy of the model : {:.4f}%".format(accuracy_score(y_test, y_pred)*100))

Accuracy of the model : 90.7407%


prediction

In [16]:
age = int(input("Enter new customer's age: "))
salary = int(input("Enter new customer's salary: "))
newCust = [[age, salary]]
res = model.predict(scaler.transform(newCust))
print(res)
if res == 1:
    print("Customer will buy.")
else:
    print("Customer won't buy.")

Enter new customer's age: 39
Enter new customer's salary: 140000
[1]
Customer will buy.
